import type { ProcessedLifeData } from '../types';

/**
 * Exports the synthesized life narrative as a formatted Markdown Dossier.
 */
export function exportLifeDossierMarkdown(data: ProcessedLifeData) {
  const { synthesis, chapters, patterns, receipts } = data;

  let md = `# ${synthesis.headline}\n\n`;
  md += `*${synthesis.subheadline}*\n\n`;
  md += `**Synthesis Year:** ${synthesis.year} | **Total Digital Receipts:** ${receipts.length}\n\n`;
  md += `---\n\n`;

  md += `## 🧭 Executive Narrative Synthesis\n\n`;
  md += `${synthesis.summaryParagraph}\n\n`;

  md += `### Key Digital Footprint Metrics\n\n`;
  for (const chip of synthesis.statChips) {
    md += `- **${chip.label}:** ${chip.value} (${chip.detail})\n`;
  }
  md += `\n---\n\n`;

  md += `## 🌌 Life Chapters & Epochs\n\n`;
  chapters.forEach((ch, idx) => {
    md += `### Epoch ${idx + 1}: ${ch.title}\n`;
    md += `*${ch.subtitle}*\n\n`;
    md += `> "${ch.narrative}"\n\n`;
    md += `- **Total Receipts:** ${ch.stats.totalReceipts}\n`;
    md += `- **Total Financial Spend:** ₹${ch.stats.totalSpend.toLocaleString()}\n`;
    md += `- **Nocturnal Ratio:** ${ch.stats.lateNightPercent}%\n`;
    if (ch.stats.topCity) {
      md += `- **Anchor Geographic Hub:** ${ch.stats.topCity}\n`;
    }
    md += `- **Dominant Themes:** #${ch.stats.dominantTags.join(', #')}\n\n`;
  });

  md += `---\n\n`;
  md += `## 💡 Discovered Named Behavioral Patterns\n\n`;
  patterns.forEach((pat, idx) => {
    md += `### ${idx + 1}. ${pat.name} [${pat.badge}]\n`;
    md += `*${pat.tagline}*\n\n`;
    md += `${pat.story}\n\n`;
    md += `**Algorithmic Analysis:** ${pat.detailedAnalysis}\n\n`;
    md += `**Key Metrics:**\n`;
    for (const m of pat.metrics) {
      md += `- ${m.label}: ${m.value}\n`;
    }
    md += `\n`;
  });

  md += `---\n\n`;
  md += `*Generated by "Your Life, In Receipts" — An Interactive Celestial Storytelling Engine.*\n`;

  // Trigger client-side download
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `life_receipts_dossier_${synthesis.year}.md`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
